version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./ssh:/var/jenkins_home/.ssh

volumes:
  jenkins_home:
