FROM node:20

RUN apt-get update && \
    apt-get install -y openssh-server rsyslog rsyslog-gnutls netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app && chown deploy:deploy /app
RUN npm install -g pm2

RUN mkdir /var/run/sshd
RUN echo 'root:dockerpassword' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN groupadd -r deploy && useradd -m -r -g deploy deploy
RUN echo 'deploy:deploypassword' | chpasswd
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

COPY keys/jenkins_deploy_key.pub /tmp/jenkins_deploy_key.pub
RUN mkdir -p /home/deploy/.ssh && \
    cat /tmp/jenkins_deploy_key.pub >> /home/deploy/.ssh/authorized_keys && \
    chown -R deploy:deploy /home/deploy/.ssh && \
    chmod 700 /home/deploy/.ssh && \
    chmod 600 /home/deploy/.ssh/authorized_keys && \
    rm /tmp/jenkins_deploy_key.pub

RUN mkdir -p /var/log/pm2 && chown -R deploy:deploy /var/log/pm2
RUN mkdir -p /var/spool/rsyslog

COPY rsyslog.conf /etc/rsyslog.conf
COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

WORKDIR /app
EXPOSE 3001 22

CMD ["/usr/local/bin/start.sh"]