FROM node:20-alpine

RUN apk add --no-cache python3 make g++ 

WORKDIR /app

COPY ./server/package*.json ./
COPY ./server/tsconfig.json ./

RUN npm install --build-from-source

COPY ./server/dist ./dist
COPY ./server/public ./public
COPY ./server/src ./src
EXPOSE 5000 

CMD ["node", "dist/index.js"]