{
 "title": "Deploy server monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"node_backend\", instance=\"deploy-server-env:5000\"}[$__rate_interval]) * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"node_backend\", instance=\"deploy-server-env:5000\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nodejs_heap_size_used_bytes{job=\"node_backend\", instance=\"deploy-server-env:5000\"} / nodejs_heap_size_total_bytes{job=\"node_backend\", instance=\"deploy-server-env:5000\"}) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nodejs_heap_size_used_bytes{job=\"node_backend\", instance=\"deploy-server-env:5000\"} / nodejs_heap_size_total_bytes{job=\"node_backend\", instance=\"deploy-server-env:5000\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(process_start_time_seconds{job=\"node_backend\", instance=\"deploy-server-env:5000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=\"node_backend\", instance=\"deploy-server-env:5000\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"node_backend\", instance=\"deploy-server-env:5000\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"node_backend\", instance=\"deploy-server-env:5000\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"node_backend\", instance=\"deploy-server-env:5000\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "nodejs_active_requests_total{job=\"node_backend\", instance=\"deploy-server-env:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request/min",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP  200 [2m]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(prometheus_http_requests_total{code=\"200\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP  300 [2m]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(prometheus_http_requests_total{code=\"300\"}[2m])) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP  400 [2m]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(prometheus_http_requests_total{code=\"400\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 500 [2m]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"node_backend\", instance=\"deploy-server-env:5000\", code=~\"500\"}[2m]))\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}